Update pulse_automated.yml

diff --git a/.github/workflows/pulse_automated.yml b/.github/workflows/pulse_automated.yml
--- a/.github/workflows/pulse_automated.yml
+++ b/.github/workflows/pulse_automated.yml
@@ -112,6 +112,57 @@ jobs:
             # fi
           fi
 
+      # Step 4: Se l'utente ha impostato fetch_all a true, scarica tutti i file nel JSON
+      - name: Recupera tutti i file dal JSON
+        if: ${{ github.event.inputs.fetch_all == 'true' }}
+        run: |
+          echo "Recuperando tutti i file OpenAPI dal file JSON"
+          all_urls=$(jq -r '.[] | .URL' openapi_files.json)
+          for url in $all_urls; do
+            echo "Scaricando $url"
+          done
+
+      # Step 5: Se il parametro server è vuoto, recuperalo dal file OpenAPI
+      - name: Recupera server dal file OpenAPI
+        if: ${{ github.event.inputs.server == '' }}
+        run: |
+          echo "Il parametro server è vuoto, recupero dal file OpenAPI"
+
+          # Definizione delle variabili di input
+          market="${{ github.event.inputs.market }}"
+          environment="${{ github.event.inputs.environment }}"
+          network="${{ github.event.inputs.network }}"
+
+          # Cerca il server nel file OpenAPI basato su market, environment e network
+          server=$(jq -r --arg market "$market" --arg environment "$environment" --arg network "$network" '
+            .servers[] | 
+            select((.description | contains($market)) and 
+                   (.description | contains($environment)) and 
+                   (.description | contains($network))) | .url' openapi.json)
+
+          # Se il server è stato trovato tramite la descrizione
+          if [ -n "$server" ]; then
+            echo "Server trovato dalla descrizione: $server"
+          else
+            echo "Nessun server trovato tramite descrizione, tentando di recuperarlo dall'URL"
+
+            # Se la descrizione non è utile, cerca il server basandoti sull'URL
+            server=$(jq -r --arg market "$market" --arg environment "$environment" --arg network "$network" '
+              .servers[] | 
+              select((.url | contains($market | ascii_downcase)) and 
+                     (.url | contains($environment | ascii_downcase)) and 
+                     (.url | contains($network | ascii_downcase))) | .url' openapi.yaml)
+
+            if [ -n "$server" ]; then
+              echo "Server trovato dall'URL: $server"
+            else
+              echo "Errore: Nessun server trovato corrispondente ai parametri forniti"
+              exit 1
+            fi
+          fi
+
+          echo "Server selezionato: $server"
+
       # - name: ValidateBaseUrl
       #   id: validateBaseUrl
       #   run: | 
